<?php

namespace AppBundle\Repository;

/**
 * IngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRepository extends \Doctrine\ORM\EntityRepository
{
}
