<?php

namespace AppBundle\Repository;

/**
 * TapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapaRepository extends \Doctrine\ORM\EntityRepository {

    public function paginaTapas($pagina=1, $numTapas=3) {
        
        //Función que devuelve las tapas para una página con un número de elementos
        $query = $this->createQueryBuilder('t')
                ->where('t.top > = 1')
                ->setFirstResult($numTapas * ($pagina - 1))
                ->setMaxResults($numTapas)
                //                ->setParameter('price', '19.99')
                //                ->orderBy('p.price', 'ASC')
                ->getQuery();
        return $query->getResult();
    }

}
